### PR TITLE
Review my PR , issue #12 ,Work on README.md

### PR DESCRIPTION
**Pull request by Rajdeep1311**

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Could you please rename the title to Chatroom-App? Also the banner, can you make it a little smaller? Do mention the issue number and the issue you will be solving with this PR.

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please add the issue number that you are solving in the PR Description. Also, I don't see the other changes I requested in the previous comment. :)

**Comment by Rajdeep1311** [comment]
Are the changes visible?

**Review by SarthakSKumar — APPROVED** [review]
Good Work @Rajdeep1311

**Comment by Rajdeep1311** [comment]
Your welcome..can you just follow me?

**Pull request merged**
